name: Deploy

on:
  push:
    branches:
      - main

permissions:
  issues: write

env:
  IMAGE_REGION: us-west1
  IMAGE_NAME: $IMAGE_REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/run-service-img/ssr-service:${{ github.sha }}



jobs:
  build-and-deploy-ssr-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssr-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.IMAGE_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        run: ./gradlew bootBuildImage --imageName=$IMAGE_NAME

      - name: Push Docker image to GCP Container Registry
        run: |
          docker push $IMAGE_NAME

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        timeout-minutes: 60
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ secrets.GH_APPROVERS }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ssr-service \
            --image $IMAGE_NAME \
            --region ${{ secrets.GCP_RUN_REGION }} \
            --platform managed \
            --allow-unauthenticated