name: Verify Build SSR Service

on:
  pull_request:
    paths:
      - ssr-service/**

jobs:
  build-ssr-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ssr-service

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build