name: Verify Build File Processor

on:
  pull_request:
    paths:
      - file-processor/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: file-processor

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Docker image
      run: docker build -f src/main/docker/Dockerfile.multistage -t quarkus/file-processor .